#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

BUN_VERSION="$(asdf latest bun)"
asdf install bun "$BUN_VERSION"
asdf set bun "$BUN_VERSION"
